### ISSUE TITLE
(1.7.10) Isis's Embrace necklace causes crash with extra inventory slots

### ISSUE THREAD

**Issue by Codelizard** [TeamMetallurgy/Atum#48]
Minecraft 1.7.10, heavily modded Forge server.

Stacktrace first, story follows:

```
Description: Ticking player

java.lang.ArrayIndexOutOfBoundsException: 150
	at com.teammetallurgy.atum.items.artifacts.ItemIsisHealing.func_77663_a(ItemIsisHealing.java:35)
	at net.minecraft.item.ItemStack.func_77945_a(Unknown Source)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:311)
	at mods.battlegear2.api.core.InventoryPlayerBattle.func_70429_k(InventoryPlayerBattle.java:188)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.localOnLivingUpdate(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.onLivingUpdate(ServerPlayerAPI.java:4891)
	at api.player.server.ServerPlayerAPI.onLivingUpdate(ServerPlayerAPI.java:4877)
	at net.minecraft.entity.player.EntityPlayerMP.func_70636_d(EntityPlayerMP.java)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295)
	at api.player.server.ServerPlayerAPI.onUpdateEntity(ServerPlayerAPI.java:5111)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Story of the issue:

After obtaining the Isis's Embrace necklace from a Pharaoh's chest on a multiplayer server I run, I was able to play for a few more seconds before I crashed with an "Internal server error". I was able to reconnect, but every time (I tried three or four times) I got the same error.

I was able to pull my playerdata file off of the server and into a freshly-created local world, and still crashed. I was eventually able to use INVEdit to remove the Isis's Embrace item from my inventory, which stopped the crashes. However, while doing that, INVEdit mentioned that slots 150-155 were invalid, which is likely the source of the "150" in the IndexOutOfBoundsException.

Those six extra item slots are added by the mod Mine & Blade Battlegear 2 ( http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291267-mine-blade-battlegear-2-bullseye-1-0-8-0 ). I appreciate that this isn't strictly speaking a problem with Atum itself as it works fine on its own; however, I would imagine that any mod that adds extra inventory slots would cause the same problem.

That should be all the relevant details, I can provide more information if necessary (and might take a crack at fixing the issue myself). And finally: thanks for making the mod! It's been fun so far.

**Comment by Glassmaker** [comment]
Umm... It could because it's a bit legacy code it was done that way.

Any way the fix should be easy :)
I will let you have a crack at if you want to :)

**Comment by Codelizard** [comment]
Probably a lot faster if you do it, actually. I'm having trouble getting the environment set up to be able to actually test it.

The line in question (ItemIsisHealing.java:35) is:

```
if (player.onGround && player.inventory.mainInventory[player.inventory.currentItem] != null && player.inventory.mainInventory[player.inventory.currentItem].getItem() == this) {
```

...and the main inventory doesn't have slots 150-155, so it's going out of the array when it checks the inventory at `player.inventory.currentItem`. It could probably be fixed by a quick range-check to ensure it's inside the bounds of the inventory, something like this:

```
if (player.onGround && player.inventory.currentItem < player.inventory.mainInventory.length && player.inventory.mainInventory[player.inventory.currentItem] != null && player.inventory.mainInventory[player.inventory.currentItem].getItem() == this) {
```

I'm reasonably sure this would fix it, but I can't get it to build to test this theory, which is why I haven't submitted a Pull Request.

This assumes that the healing items can't end up in additional item slots, which is reasonable for Mine & Blade (the extra slots can only hold weapons and shields) but may or may not be reasonable for other mods that add extra slots.

**Comment by Glassmaker** [comment]
Okeo, but the problem with this solution is the effect won't active if the item in the extended slots (slots 150-155).

So, a better solution is to get the current item in compatible way in vanilla and battlegear 2.

Looking at Battlegear 2 source, you can see they are [replacing the player inventory](https://github.com/Mine-and-blade-admin/Battlegear2/blob/1.7.10/battlegear%20mod%20src/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch#L23) with [their compatible one](https://github.com/Mine-and-blade-admin/Battlegear2/blob/1.7.10/battlegear%20mod%20src/minecraft/mods/battlegear2/api/core/InventoryPlayerBattle.java), and they are [overriding getCurrentItem()](https://github.com/Mine-and-blade-admin/Battlegear2/blob/1.7.10/battlegear%20mod%20src/minecraft/mods/battlegear2/api/core/InventoryPlayerBattle.java#L113-L116) to get the item if the extra slots are selected.

Upon that, we can replace the array parts with `player.inventory.getCurrentItem()`, and not worry about ArrayIndexOutOfBoundException :)

I will be taking it a step further and use `player.getHeldItem()` just in case someone decides to do something with the player entity and accidentally make not work ;)

So, Final code will be
```java
if (player.onGround && player.getHeldItem() != null && player.getHeldItem().getItem() == this) {
```

**Comment by Codelizard** [comment]
Ah, I see! Thank you for the explanation. That is a much better solution.
